### ISSUE TITLE
install error: ImportError: DLL load failed while importing _c: The specified module could not be found.

### ISSUE THREAD

**Issue by AlbertJNU** [KinglittleQ/torch-batch-svd#27]
**Describe the problem**
When I finished the "python setup.py install", I met the problem "ImportError: DLL load failed while importing _c: The specified module could not be found. " importing the torch_batch_svd package.
![image](https://github.com/KinglittleQ/torch-batch-svd/assets/69504510/77d6286b-6cb8-4015-97c6-d072cec5713e)

**Error message**
Python 3.8.16 (default, Mar  2 2023, 03:18:16) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch_batch_svd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\AORUS\.conda\envs\antransform\lib\site-packages\torch_batch_svd-1.1.0+c0a9611-py3.8-win-amd64.egg\torch_batch_svd\__init__.py", line 1, in <module>
    from .batch_svd import svd
  File "C:\Users\AORUS\.conda\envs\antransform\lib\site-packages\torch_batch_svd-1.1.0+c0a9611-py3.8-win-amd64.egg\torch_batch_svd\batch_svd.py", line 3, in <module>
    from . import _c
ImportError: DLL load failed while importing _c: 找不到指定的模块。

**Environments**
1. windows
2. CUDA v12.0
3. torch 1.7.1
4. Python 3.8

Do you have met the same problem, I would be grateful if you could point out the error and suggest a correction.

**Comment by ZephyrZhang3** [comment]
I have the same problem. Do you find any way to fix it?

**Comment by toontran** [comment]
I had the same problem, and I worked around it by installing the package and use globally instead:
```
export CUDA_HOME=/your/cuda/home/directory/
python setup.py install --user
```
